
# Remember to set service.type=ClusterIP if you are using an ingress
ingress:
  enabled: true
  hostname: demo-argo.dr-team-4.dev-ck8s.com
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

# Provide a custom message
message: test-this-is-from-git


service:
  type: ClusterIP
  port: 80

deployment:
  replicaCount: 3
  container:
    image:
      repository: "harbor.dr-team-4.dev-ck8s.com/pavan/hello-ck8s:v1"
      tag: v1
      pullPolicy: IfNotPresent
    port: 8080

  # Currently only linux images on amd64 architecture are supported - support for arm64 and windows/amd64 coming ...
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64

  resources:
      limits:
        memory: 200Mi
        cpu: 1
      requests:
        memory: 100Mi
        cpu: 100m

  tolerations: []

  affinity: {}