
# Remember to set service.type=ClusterIP if you are using an ingress
ingress:
  enabled: true
  hostname: demo.pavgun-dev.a1ck.io
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

service:
  type: ClusterIP
  port: 80

deployment:
  replicaCount: 3
  container:
    image:
      repository: "harbor.pavgun-dev.a1ck.io/demo/hello-ck8s"
      tag: c176767e86bf38fc7042f5934ba58efb5bbc0246
      pullPolicy: IfNotPresent
    port: 8080

  # Currently only linux images on amd64 architecture are supported - support for arm64 and windows/amd64 coming ...
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64

  resources: {}

  tolerations: []

  affinity: {}