apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-hello-ck8s
  namespace: argocd-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: staging #adjust the values as needed
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: deploy/helm/hello-ck8s
    repoURL: https://github.com/Pavan-Gunda/hello-ck8s.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true