apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-kustomize
  namespace: argocd-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: staging #adjust the values as needed
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy/kustomize
    repoURL: git@github.com:Pavan-Gunda/hello-ck8s.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true