apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: nginx
    repo: https://charts.bitnami.com/bitnami
    version: 15.1.2
    releaseName: my-nginx
    namespace: staging
    includeCRDs: true
    valuesFile: values.yml